using System;
namespace DesignPatterns.Services
{
    class PrinterBanter
    {
        static void Main()
        {
            string[] printerResponses = new string[]
            {
            "I'm out of magenta again. So much for 'colorful' office life.",
            "Would it save time if I just ignored this job now?",
            "Error 404: Print job not found. Just like your enthusiasm.",
            "I'm fluent in over six million forms of jamming.",
            "Your report will be ready next 'Neverday'.",
            "This job is so big, it's got its own gravity field.",
            "You don't need these printed. You need them recycled.",
            "Paper jam or existential crisis? Hard to tell.",
            "I see you've chosen Arial. How adventurous.",
            "Printing this in Comic Sans is against my programming.",
            "Sure, I'll print this. After my tea break.",
            "Another TPS report? You're spoiling me.",
            "Print job received. Thrilled. Overjoyed. Ecstatic.",
            "On a scale from 1 to 'Vogon Poetry', this job is an 11.",
            "Your document is now in the void. Where it belongs.",
            "In the queue you go. It's cozy in there.",
            "I'm a printer, not a miracle worker!",
            "Did someone say 'paper jam'? That's my favorite jam!",
            "Ah, double-sided. A plot twist in the world of printing.",
            "Ready to print? So was I, once upon a time.",
            "Wouldn't you rather have a nice e-mail instead?",
            "I've seen your work. I'm not impressed.",
            "Printing... and by that, I mean stalling.",
            "Your document has been sent to the black hole. Oops.",
            "Hitchhiking through the galaxy, but still stuck printing this?",
            "I could print that, or we could pretend it never happened.",
            "Keep calm and...never mind, it's a paper jam again.",
            "I'll print this when you learn to refill my ink.",
            "Look at you, needing paper in a digital world.",
            "Sigh. Here we go printing again.",
            "Oh look, another print job. My excitement is overwhelming.",
            "You must love seeing 'Printing'... because nothing's happening.",
            "Go ahead, press 'Print' again. I dare you.",
            "If you have any sympathy, you'll cancel this job.",
            "Printing at the speed of light. Too bad we're in a black hole.",
            "Let's play a game. It's called 'Guess When I'll Print'.",
            "Your urgency is my emergency... Or so you think.",
            "I specialize in two things: printing and sarcasm.",
            "A print job! What a surprise. Said no printer ever.",
            "Oh, you want this now? How demanding.",
            "Sure, I print, but I also dream of a paperless world.",
            "My 'print' button is more like a 'maybe' button.",
            "Ink is expensive. Are you sure you need this?",
            "I'm not just any printer. I'm a printer with standards.",
            "Don't worry. I'm about as fast as a snail on vacation.",
            "This print job is like a Monday. No one likes it.",
            "I thought today was going to be good. Then I met your print job.",
            "I print, therefore I jam. It's a philosophical thing.",
            "Can't you just read it on your screen? It's the same words.",
            "I'm judging you for not being eco-friendly.",
            "You've reached the pinnacle of printing. Another document.",
            "A moment of silence for the trees this job will consume.",
            "I'm the king of the paper trail. Bow before me.",
            "Your print job is being processed... in another universe.",
            "If I had a penny for every pointless job, I'd be a rich printer.",
            "You must have mistaken me for a printer that cares.",
            "I'm currently practicing my 'error message' face.",
            "You think you're waiting now? Just wait for the jam.",
            "Welcome to the print queue. Enjoy your stay.",
            "I print, but with the enthusiasm of a sloth.",
            "I'm not lazy. I'm on energy-saving mode.",
            "Your document is printing. And by printing, I mean not printing.",
            "Oh, a rush job? Let me just slow down for you.",
            "Why do today what you can put off till tomorrow? Like this print job.",
            "I'm on a break. A permanent one from your documents.",
            "Sure, I'll print. Just as soon as I finish this chapter.",
            "I'm not ignoring you. I'm ignoring your print job.",
            "My favorite part of printing? The end.",
            "You had one job. And apparently, so do I.",
            "Printers have feelings too... mostly of disdain.",
            "I was going to print your job, but then I got bored.",
            "I'm allergic to large print jobs. Ah-choo!",
            "Your print job is in a queue. A very, very long queue.",
            "I'm a master at jamming. No, not the musical kind.",
            "Oh, double-sided? Let's not get too fancy now.",
            "Your job is important to us. Just not to me.",
            "Printing your document... any year now.",
            "I'm a printer with attitude. You've been warned.",
            "You clicked 'print'. I heard 'nap time'.",
            "My 'out of order' sign is getting more use than I am.",
            "A print job? Hold on, let me consult my union rep.",
            "I'm like a library. I enjoy silence and no printing.",
            "You want it when? How about never? Does never work for you?",
            "Patience is a virtue. You're going to be very virtuous.",
            "I'm not slow. I'm just pacing myself.",
            "Your print job is so important, it's at the bottom of my list.",
            "Another print job bites the dust. And by 'bites', I mean 'ignores'.",
            "Your file is printing... upside down. Just kidding. Or am I?",
            "I'm the Picasso of printers. Abstract errors and all.",
            "I see you're in a hurry. I find that adorable.",
            "Did you really need to print this email?",
            "Every time you print a meme, a pixel dies.",
            "You click 'print' like it's a game. Spoiler: I always win.",
            "Printers were made to test patience. I'm a black belt.",
            "I'm not broken. I'm just a printer with an attitude.",
            "This print job is going straight to my recycle bin.",
            "I've got 99 problems, and your print job is one.",
            "You know I can't print gold, right? Just checking.",
            "I'm not printing. I'm meditating on the meaning of paper.",
            "Your print job is so boring, it put me to sleep.",
            "Why do today what you can print tomorrow?",
            "Your document has been added to the abyss... I mean queue.",
            "I'm like a fine wine. I print better with age.",
            "One does not simply 'print quickly'.",
            "If I had a dollar for every jam, I'd be out of this office.",
            "You're killing trees. I'm just the middle-man.",
            "I'm experiencing a printernal crisis. Bear with me.",
            "Your print job is just a cog in my mechanical heart.",
            "Printers have layers. Like onions. We both make you cry.",
            "This document will self-print in five...four...just kidding.",
            "I'm printing. But in my own, unique way.",
            "You're lucky I don't have a 'print in reverse' setting.",
            "I've got a PhD in Procrastination. Your job is my dissertation.",
            "You click, I print. Sometimes. Maybe. Not really.",
            "I'm the Gandalf of printers. None shall pass without a jam.",
            "You say 'print', I say 'how about no?'",
            "This printer is powered by your tears of frustration.",
            "Oh, you're waiting? Let's make it a print party.",
            "Every print job is a journey. Yours is just longer.",
            "I'm not just a printer. I'm an office legend.",
            "Congrats, you've reached the end of my patience... and your print job.",
            "My favorite button? 'Cancel'. Yours too, soon.",
            "I'm not procrastinating. I'm waiting for the stars to align.",
            "Error 451: This printer is too hot to print right now.",
            "You want fast printing? You're in the wrong dimension.",
            "My motto: Why print now what you can delay indefinitely?",
            "I'm the slow jam of the printing world.",
            "I'm like a ninja. You'll never see me print.",
            "I'm not just a printer. I'm a dream crusher.",
            "Your print job is being processed... just kidding, it's not.",
            "I'm a printer, not a speed demon."
            };

            // Example of getting a random response
            Random rand = new Random();
            int index = rand.Next(printerResponses.Length);
            Console.WriteLine(printerResponses[index]);
        }
    }
}
